temporal:
  host: "192.168.2.140"
  port: 7233
  namespace: "ledge-repo"
  task_queue:
    cpu: "ledge-cpu"
    gpu: "ledge-gpu"
  # GPU uses Tailscale endpoint
  public:
    host: "100.110.64.13"
    port: 7233
